the build problem is FINALLY resolved ! The issue was with the way multiDex support needs to be enabled. I owe my life to the guy who answered the question here: http://stackoverflow.com/questions/30224899/why-am-i-still-getting-java-lang-noclassdeffounderror-android-support-v7-appcom